

CREATE TABLE Professor (
  ProfessorID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Nome VARCHAR(50) NOT NULL,
  CursoID INT FOREIGN KEY REFERENCES Curso(CursoID),
  LoginID INT FOREIGN KEY REFERENCES Login(LoginID)
);

CREATE TABLE Admin (
  AdminID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Nome VARCHAR(50) NOT NULL,
  LoginID INT FOREIGN KEY REFERENCES Login(LoginID)
);

CREATE TABLE Curso (
  CursoID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Nome VARCHAR(50) NOT NULL
);

CREATE TABLE Disciplina (
  DisciplinaID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Nome VARCHAR(50) NOT NULL,
  CursoID INT FOREIGN KEY REFERENCES Curso(CursoID)
);
CREATE TABLE Estudante (
  EstudanteID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Nome VARCHAR(50) NOT NULL,
  CursoID INT FOREIGN KEY REFERENCES Curso(CursoID),
  MatriculaID INT FOREIGN KEY REFERENCES Matricula(MatriculaID),
  LoginID INT FOREIGN KEY REFERENCES Login(LoginID)
);
CREATE TABLE Matricula (
  MatriculaID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  DisciplinaID INT FOREIGN KEY REFERENCES Disciplina(DisciplinaID)
);

CREATE TABLE Login (
  LoginID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Username VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL
);
